# Generated by Django 2.0.6 on 2018-06-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoveReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(max_length=12)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imdb_link', models.URLField(max_length=255)),
                ('director', models.CharField(max_length=99)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='movereview',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Movie'),
        ),
        migrations.AddField(
            model_name='movereview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Reviewer'),
        ),
    ]
