# Generated by Django 2.0.6 on 2018-06-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoveReview',
            new_name='MovieReview',
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_link',
            field=models.URLField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
